### ISSUE TITLE
help cloning a dropbox repo

### ISSUE THREAD

**Issue by nileio** [anishathalye/git-remote-dropbox#101]
thanks for sharing the extension.

I am not sure what I am missing here. I already have a git repo on dropbox which I am using for a while with local dev. I am sure it is there and sure had a number of branches etc.

I setup the extension on a remote host and setup the extension as documented , have my oAuth key and everything in the right location.
When I try to clone my repository I receive
```
info: repository is empty
info: no default branch on remote
warning: You appear to have cloned an empty repository.
```
tried it with specifying the branch `master` that I am sure exists on my dropbox and received
```
info: repository is empty
info: no default branch on remote
fatal: Remote branch master not found in upstream origin
```
tried the other way where I specify the dropbox folder as a `remote` after `git init` - still same issue

Is there a way to debug what is going on ? it is not an Auth issue I suppose because I tried just giving it any other directory, and then it returned an error that the directory doesn't exist., so it is able to access my dropbox folders.

Any switches to get verbose output or debug output, what could be the issue here?

**Comment by anishathalye** [comment]
> I already have a git repo on dropbox which I am using for a while with local dev.

git-remote-dropbox uses a custom on-disk format. If you create a git repo in your dropbox synced folder by navigating into there and doing a `git init`, that is not compatible with git-remote-dropbox.

You can solve this issue by creating a new remote in your original git repo and pushing to it. Suppose your Dropbox synced folder was `/home/nileio/dropbox`, and the original git repo was in `/home/nileio/dropbox/code/project` (created with a `git init`). You can navigate into that repo and add a new git remote, `git remote add dropbox dropbox:///repos/project` (doesn't matter where you put it, as long as it's some new location). Then you push everything to that remote, and then you can clone from there, with a `git clone dropbox:///repos/project`. You can keep this local clone of your repo _outside_ of the directory synced by dropbox, and you should also update your dropbox sync settings to not sync the `repos` directory (git-remote-dropbox will interact with it directly).

**Comment by nileio** [comment]
@anishathalye thanks for reply. 
> You can solve this issue by creating a new remote in your original git repo and pushing to it. Suppose your Dropbox synced folder was `/home/nileio/dropbox`, and the original git repo was in `/home/nileio/dropbox/code/project` (created with a `git init`). You can navigate into that repo and add a new git remote, `git remote add dropbox dropbox:///repos/project`

I suppose this means that I need to install git-remote-dropbox extension on the machine which includes my original git repo. because otherwise that `dropbox://` will not be recognised. Is this correct?


> Then you push everything to that remote, and then you can clone from there, with a `git clone dropbox:///repos/project`

Now I am a bit lost! If I push to my `remote` (which is the dropbox new folder /repos/project)- why do I need to do any clone then ? 

> You can keep this local clone of your repo _outside_ of the directory synced by dropbox, and you should also update your dropbox sync settings to not sync the `repos` directory (git-remote-dropbox will interact with it directly).

not sure I am following now! perhaps we need a little picture!
Can you confirm ?

Let's say My Dropbox looks like this

/code/project -> this is already under version control by git, created originally using with stock `git` using `git init` or `git clone` for example..

/code/copyproject-> this is empty folder

1. install git-remote-dropbox extension on the machine where dropbox is installed (in order to have the mount point to dropbox and sync etc.).

2. Now
```
#
cd <myDropboxmount>/code/project
git remote add dropbox dropbox:///code/copyproject
git push remote origin
```
?

**Comment by nileio** [comment]
Aah I think I got it now ! It creates the folder on first push and init it as git repo for use by the extension.
Then you mention then I can at a remote host which has the extension installed do a `git clone`
Ok makes sense now.

Now I am doing that, the only issue I am facing is that it is extremely slow  - large repo. My normal operations on Dropbox is pretty good as a normal git repo. Is there any flags or something to do about that?

**Comment by anishathalye** [comment]
It's fast with normal operations on Dropbox because the syncing is deferred: git makes changes locally, and those changes are eventually propagated to the Dropbox servers. git-remote-dropbox actually has to push everything up to Dropbox. The first push will be the slowest, because you're pushing the entire repo, and future ones should be much faster.

If you run with `-v`, do you see a better error message?

I haven't debugged this thoroughly, but I think Dropbox's API might do some kind of rate limiting; if uploading a whole repo at once is too much, you could try doing it in parts. E.g. if your repo has 100 commits and you're on the master branch, start off with a `git push dropbox master~50:master`, and then do a final `git push dropbox master`.

**Comment by nileio** [comment]
thanks for reply. I ended up using `rsync` for my needs which seem to work well.
