### ISSUE TITLE
report exception details

### ISSUE THREAD

**Issue by tbc** [anishathalye/git-remote-dropbox#19]
```
index a369f1c..d3f6930 100755
--- a/git-remote-dropbox
+++ b/git-remote-dropbox
@@ -671,8 +671,8 @@ def main():
     helper = Helper(token, url)
     try:
         helper.run()
-    except Exception:
-        stderr('error: unexpected exception\n')
+    except Exception as e:
+        stderr('error: unexpected exception {}\n'.format(e))
     except KeyboardInterrupt:
         # exit silently with an error code
         exit(1)
```

**Comment by tbc** [comment]
Sorry, I should have looked at CONTRIBUTING.md and created a PR, but since this issue is open I'll wait for your response.

**Comment by anishathalye** [comment]
Hmm, that would provide more information, but the goal of #9 was to have more human-readable exceptions, not printing out Python exception information or a stack trace.

**Comment by tbc** [comment]
I understand. I'm still familiarizing myself with the operation of git-remote-dropbox. I'll keep watching and look forward to the day I have something to contribute.

**Comment by anishathalye** [comment]
Okay, sounds good.
