### ISSUE TITLE
"unexpected exception"

### ISSUE THREAD

**Issue by of6** [anishathalye/git-remote-dropbox#22]
Installed git-remote-dropbox script to `/usr/local/bin/git-remote-dropbox` 

Installed `dropbox-sdk-python`

Created a test repo in a dropbox folder. When trying to pull from this ends up with this generic message. What does this mean?

```
$ git clone "dropbox://Development/gittest"
Cloning into 'gittest'...
error: unexpected exception
```

I'm guessing it's not able to connect to dropbox?
I have a file `~/.git-remote-dropbox.json` with the oauth token 

tested the token via python console, which was able to connect.

```
>>> import dropbox
>>> dbx = dropbox.Dropbox("XXXXXX-TOKEN")
>>> dbx.users_get_current_acccount()
FullAccount(account_id=.............)
```

What am I missing here?

OS X 10.11, Python 2.7.10

**Comment by anishathalye** [comment]
Sorry, the error reporting needs some work... (see #9).

What do you mean by "created a test repo in a dropbox folder"? Like did you make the `/Development/gittest` folder in Dropbox and put stuff in it? You don't need to do that, you should push your local repository directly (you could even delete the folder on Dropbox first). Just a `git push -u origin master` should do it.

**Comment by of6** [comment]
Just tried that, same error.

Your instructions said you could clone repo's inside Dropbox...

--

To clone repositories in folders or shared folders mounted in your Dropbox, you can run:

``git clone "dropbox://path/to/repo"``

**Comment by anishathalye** [comment]
Oh what? Well, could you try following [these instructions](https://github.com/anishathalye/git-remote-dropbox/issues/15#issuecomment-135314527) so we could get some more information about what's going on?

By the way, Git's on-disk format is not quite the same as git-remote-dropbox's on-disk format, so you can't just copy a Git repo onto Dropbox and have it work.

**Comment by of6** [comment]
Sure. Here's the output

```
$ GIT_TRANSPORT_HELPER_DEBUG=1 git push origin master
Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Capabilities complete.
Debug: Remote helper: -> option progress true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> option verbosity 1
Debug: Remote helper: Waiting...
Debug: Remote helper: <- ok
Debug: Remote helper: Waiting...
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-dropbox", line 687, in <module>
    main()
  File "/usr/local/bin/git-remote-dropbox", line 677, in main
    helper.run()
  File "/usr/local/bin/git-remote-dropbox", line 347, in run
    self._do_list(line)
  File "/usr/local/bin/git-remote-dropbox", line 372, in _do_list
    refs = self._get_refs(for_push=for_push)
  File "/usr/local/bin/git-remote-dropbox", line 613, in _get_refs
    if not isinstance(e.reason, dropbox.files.ListFolderError):
AttributeError: 'ApiError' object has no attribute 'reason'
Debug: Remote helper quit.
```

**Comment by anishathalye** [comment]
OH, okay. So... the Dropbox API is still in preview, so they are making breaking API changes. See #20.

For now, you could apply that patch yourself, and it should work just fine.

**Comment by of6** [comment]
Ah! Works great! Thanks for you help!
