### ISSUE TITLE
PY2 variable is not readily available on my OS X 10.11 (Xcode, Python 2.7)

### ISSUE THREAD

**Issue by floatingatoll** [anishathalye/git-remote-dropbox#29]
Hi, after doing "pip install git-remote-dropbox" on an OS X 10.11 system (using Xcode, not Homebrew), I encountered an error during git push that traced to the following issue:

https://github.com/Eugeny/reconfigure/pull/17

I was eventually able to compel my boring, stock OS X python install into a reasonable enough version of six to provide the PY2 constant you seek using ```sudo pip install --force-reinstall -I --no-cache-dir six```.

Please consider applying something akin to the pull request above instead to improve compatibility with OS X.

**Comment by anishathalye** [comment]
Hmm, I'm confused. We don't use `six` at all in git-remote-dropbox, at least not directly.

It looks like the [Dropbox Python SDK](https://github.com/dropbox/dropbox-sdk-python/) uses six, though: https://github.com/dropbox/dropbox-sdk-python/blob/master/setup.py#L20

**Comment by floatingatoll** [comment]
Oh. I'm sorry :( Never mind, then. (Works great, by the way. Thank you for writing this!)
