### ISSUE TITLE
Why is all the code in __init__.py ? 

### ISSUE THREAD

**Issue by yask123** [anishathalye/git-remote-dropbox#30]

**Comment by anishathalye** [comment]
I think some single-file Python packages are structured this way, e.g. https://github.com/rfk/git-remote-hg. Some aren't, though, like https://bitbucket.org/gutworth/six.

I don't think it really matters.

**Comment by yask123** [comment]
Yea, I think that too.
I raised this question because I was curious if there was some reason I didn't know.
