### ISSUE TITLE
Supporting encryption may allow a unique Use Case

### ISSUE THREAD

**Issue by kasajian** [anishathalye/git-remote-dropbox#31]
I believe that today, if you don't want to trust the cloud with your source code, you really can't use github, gitlab, vso, bitbucket, or even dropbox, because if you don't want your source code outside your premises, then it limits your options to zero.

But, what if you were to perform client side encryption such that it was transparent to the git user.   Ideally this would be done to a file-system that git talks to locally, and what gets pushed the cloud doesn't even look like a git repository.   This, as opposed to, using an existing git repository and then performing client-side encryption to the individual files.

It seems to me that git-remote-dropbox is in a unique scenario.  Since it's already providing its own protocol, it can (and does) store the actual files in any way that they like.

So if it encrypted the data, with the private key being local, you can truly store stuff on the cloud that cannot be looked at by anyone other than someone who has a private key.

**Comment by anishathalye** [comment]
Interesting idea!

**Comment by anishathalye** [comment]
Closing due to age. I'm not currently planning on implementing this functionality. Also, maybe the right way to implement this would be separate from git-remote-dropbox itself, such that the encryption helper could be layered on top.
