### ISSUE TITLE
Rougly how many files does this generate?

### ISSUE THREAD

**Issue by Johnsel** [anishathalye/git-remote-dropbox#37]
Dropbox has a +- 300k limit for reasonable performance. How many files should I expect per repo?

**Comment by anishathalye** [comment]
You can count using `git rev-list --objects HEAD | wc -l`

**Comment by anishathalye** [comment]
Going to assume this has been resolved; if you have any other questions, feel free to re-open this issue.

**Comment by Johnsel** [comment]
Sorry for leaving you in the dark. Google filed the notifications under a tag I don't usually check. I will try the command you suggested and if I have any questions will post back here. Thanks!
