### ISSUE TITLE
Is it possible to make a changelog?

### ISSUE THREAD

**Issue by s7jones** [anishathalye/git-remote-dropbox#38]
I've noticed you've updated the version of this. Is it possible to get a changelog summarizing the major details as they happen?

**Comment by anishathalye** [comment]
Hmm, this was a minor version update, not a major version update.

I'm not sure if this project is big enough that we need a changelog. The Git log might be good enough. You can see what's changed by looking at the output of `git log v0.1.0..v0.2.0`:

(with the `--oneline` option added)

```
1cbcec6 Release 0.2.0
666c083 Add progress indicators for pushing and fetching
9b936e6 Merge branch 'grawity/xdg'
71632c6 Update README.md for new configuration path
53f2871 Read configuration file from XDG location
```

**Comment by s7jones** [comment]
Thanks, I ended up using those `git log` commands as well as `git log v0.1.0 -1 --date=iso` to quickly make a markdown changelog #39.

The steps used to make it:

1. Use `git log v0.1.0..v0.2.0` to find list of commits between versions.
2. Use `git log v0.1.0 -1 --date=iso` to find the relevant date.
3. Use a simple regex `s/^/* /` to add bullets to the start of the commits.

**Comment by anishathalye** [comment]
Closing this now, see #39 for more info.
