### ISSUE TITLE
Package for distribution

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/git-remote-dropbox#4]
It would be good to package this script for distribution and release it in such a way that it can be installed in a single command with `brew` or `pip` or something similar.

This depends on #3 and probably requires that the Dropbox Python SDK being released on PyPI.

**Comment by HellerCommaA** [comment]
dropbox==2.2.0 is the newest version of the dropbox module on pypi. (requires urllib3==1.11)

**Comment by anishathalye** [comment]
The naming convention is a bit weird, but [dropbox 2.2.0 on pypi](https://pypi.python.org/pypi/dropbox/2.2.0) actually uses Dropbox API v1. It was last updated in September 2014.

I'm using the Python SDK for Dropbox API v2 (which is still in [preview](https://github.com/dropbox/dropbox-sdk-python)).

**Comment by HellerCommaA** [comment]
ooOOOoohhhhh

**Comment by anishathalye** [comment]
It looks like dropbox 3.x (currently 3.1.2) is [now on pypi](https://pypi.python.org/pypi/dropbox).

I think this is still a preview release, though.

**Comment by anishathalye** [comment]
Okay, this is finally done (in 2b8594483ae882ec0941e2ec49e5e10c8c0f873c)!!

We're using `dropbox>=6.1,<7`, which should be okay. The API (https://github.com/dropbox/dropbox-sdk-python) is still in preview though. If there are backwards-incompatible changes, hopefully they respect semantic versioning…
