### ISSUE TITLE
Integration with other apps?

### ISSUE THREAD

**Issue by austinstudio** [anishathalye/git-remote-dropbox#44]
Hey, I am using Sourcetree to connect with my git repositories.  I was able to connect and push to a remote using the command line but can't get Sourcetree to do the same.  It adds the remote properly and shows me the tag on the timeline to show that I am updated but won't let me push.

This is the error I get:

    git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v -- tags origin refs/heads/master:refs/heads/master 
    fatal: Unable to find remote helper for 'dropbox'
    Completed with errors, see above

Any ideas on how to integrate with the tool?  It would really help.

**Comment by anishathalye** [comment]
I don't use Sourcetree, but it seems like this issue is caused because `git-remote-dropbox` is not found on your `$PATH` when you're running Sourcetree.

Does Sourcetree let you explicitly set / add things to the path?

**Comment by anishathalye** [comment]
Looks like info here might help: https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly

**Comment by austinstudio** [comment]
I used the following and it worked.

    open /Applications/SourceTree.app/Contents/MacOS/SourceTree

Thanks for the help.  I would have had no idea that this was the issue.
