### ISSUE TITLE
warning: remote HEAD refers to nonexistent ref, unable to checkout.

### ISSUE THREAD

**Issue by jg** [anishathalye/git-remote-dropbox#45]
I'm getting the above warning after cloning a repository. No branch is listed in 'git branch' right after cloning.

Only after a 'git pull' master gets checked out & the repo becomes functional. 

git-remote-dropbox (0.2.2)
dropbox 2015.10.28
git 2.7.4

**Comment by anishathalye** [comment]
This is explained in the last bullet point here: https://github.com/anishathalye/git-remote-dropbox#notes
