### ISSUE TITLE
Is this the correct path format? It claims the repo is empty

### ISSUE THREAD

**Issue by astoeckley** [anishathalye/git-remote-dropbox#46]
I have in my dropbox folder repos/test2 directory, which is a git repo with a committed file. But then I do this:

```
git clone "dropbox://repos/test2"
Cloning into 'test2'...
info: repository is empty
warning: You appear to have cloned an empty repository.
```

It claims it is empty, and git status in my new cloned dir says it is an initial commit.

Why is this?

**Comment by anishathalye** [comment]
git-remote-dropbox's on-disk format isn't exactly the same as Git's format (e.g. we don't do packfiles).

See https://github.com/anishathalye/git-remote-dropbox/issues/22#issuecomment-148544185 and https://github.com/anishathalye/git-remote-dropbox/issues/22#issuecomment-148560656.

So you need to create a repo locally, push it to Dropbox using git-remote-dropbox, and then you can clone it using git-remote-dropbox.

**Comment by astoeckley** [comment]
Thanks, I got it working.

This is really quite fascinating. All the stars and forks on this repo seem to suggest it is widely used. In your honest opinion, is this worthy of maintaining production code?

**Comment by anishathalye** [comment]
Yeah, it does seem like a bunch of people use it (I wish I had exact statistics, though).

I do believe it is stable enough. I personally use it for a bunch of my own projects.

Also, the way git-remote-dropbox is designed, it's really easy to reconstruct a git repo given just the folder from Dropbox (see [here](https://github.com/anishathalye/git-remote-dropbox/issues/14)). So this should give you additional peace of mind.

**Comment by astoeckley** [comment]
One thing that would be kinda cool is if I could use the tools in SourceTree (a popular Git GUI), but iti appears it can't easily link up with the helper (see attached). Not a big deal, I can change my habits a bit.

<img width="600" alt="screen shot 2016-12-17 at 01 22 31" src="https://cloud.githubusercontent.com/assets/4611759/21282641/859ef646-c3f7-11e6-9697-b1564756f637.png">

**Comment by astoeckley** [comment]
re: my last comment, i just found this so I shall try: https://github.com/anishathalye/git-remote-dropbox/issues/44

**Comment by anishathalye** [comment]
Yeah, that should work for you.
