### ISSUE TITLE
error: exception while downloading: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by hgirish** [anishathalye/git-remote-dropbox#47]
When issuing git clone, I am getting error: exception while downloading: a bytes-like object is required, not 'str'.
Repo was created on my laptop, and pushed to dropbox. Now I am trying to clone it to my work computer.

Python version 3.6

**Comment by anishathalye** [comment]
Welp. Wanna try following this to see if we can get some more info about the error: https://github.com/anishathalye/git-remote-dropbox/issues/36#issuecomment-243565373

**Comment by hgirish** [comment]
I am not familiar with python. I changed __init__.py line for  459 to
except Exception:
            import traceback
            traceback.print_exc()
            self._fatal('exception while writing objects')
from
except Exception:            
            self._fatal('exception while writing objects')

then I ran git clone again
but I got same result.

**Comment by anishathalye** [comment]
Seems like a bytes vs string issue… I thought eeb759c3da7e226f1530cd67877156a107650d67 fixed all those issues, but maybe not?

**Comment by hgirish** [comment]
FYI, I am running windows 10.
Below is what I get after setting GIT_TRANSPORT_HELPER_DEBUG=1

Debug: Remote helper: -> capabilities
Debug: Remote helper: Waiting...
Debug: Remote helper: <- option
Debug: Got cap option
Debug: Remote helper: Waiting...
Debug: Remote helper: <- push
Debug: Got cap push
Debug: Remote helper: Waiting...
Debug: Remote helper: <- fetch
Debug: Got cap fetch
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Capabilities complete.
Debug: Remote helper: -> option progress true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> option verbosity 1
Debug: Remote helper: Waiting...
Debug: Remote helper: <- ok
Debug: Remote helper: Waiting...
Debug: Remote helper: <- c550d5d9a3198d2xyzz14b5117f806d172b22d348 refs/heads/master
Debug: Remote helper: Waiting...
Debug: Remote helper: <-
Debug: Read ref listing.
Debug: Remote helper: -> option cloning true
Debug: Remote helper: Waiting...
Debug: Remote helper: <- unsupported
Debug: Remote helper: -> fetch c550d5d9a3198d2xyzz14b5117f806d172b22d348 refs/heads/master

Debug: Remote helper: Waiting...
error: exception while downloading: a bytes-like object is required, not 'str'
Debug: Remote helper quit.

**Comment by anishathalye** [comment]
Oh hmm maybe it's a Windows issue - #13 has some related info

**Comment by anishathalye** [comment]
fixed in #50
