### ISSUE TITLE
Streamline configuration process

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/git-remote-dropbox#5]
Currently, setting up git-remote-dropbox involves creating a Dropbox API app and then generating an OAuth token for it.

This takes about a minute to do, and it's a one-time-thing, but it would be good if it could be streamlined to take even less time. It would be great if the helper could prompt the user to go through some kind of OAuth setup flow.

Doing this in such a way that we don't have to hard-code API app secrets would be great. (I'm not sure if it's possible though...)

**Comment by arpit1997** [comment]
It is not possible to make authorization requests for token without hard-coding the API secret. I suggest that you could put a tiny server to handle this by storing API secrets there and returning the token back to the application. you may refer [this.](https://www.dropbox.com/developers-v1/core/start/python)

**Comment by anishathalye** [comment]
Closing due to age.

Also, even though the current setup is slightly cumbersome (takes 1-5 minutes), it is trustless, in the sense that nobody needs to trust that some service that I run is doing the right thing. This seems like a nice property to have.
