### ISSUE TITLE
Are there any guarantees that the remote git repository will always be correct?

### ISSUE THREAD

**Issue by s7jones** [anishathalye/git-remote-dropbox#52]
I am wondering if I can use git-remote-dropbox to use Dropbox as a backup for my git repositories.

Is there any guarantees that this tool will maintain data integrity?

**Comment by anishathalye** [comment]
Yes, git-remote-dropbox maintains data integrity. See [this blog post](http://www.anishathalye.com/2015/08/19/git-remote-dropbox/) and the [design doc](https://github.com/anishathalye/git-remote-dropbox/blob/master/DESIGN.rst) for an explanation.

**Comment by anishathalye** [comment]
Going to assume this is resolved
