### ISSUE TITLE
Running git-remote-dropbox on Windows

### ISSUE THREAD

**Issue by chess123mate** [anishathalye/git-remote-dropbox#53]
I am currently opening up a command prompt, navigating to a test folder, and typing in

git-remote-dropbox clone "dropbox://GitTest"

However, it doesn't do anything. I just realized I can type further instructions in, but I'm not sure what's expected (and repeating the command just outputs "error: unsupported operation: clone "dropbox://GitTest" ")

I have installed Python 3.6 and then git-remote-dropbox. I have generated a token to use for dropbox and placed the .git-remote-dropbox.json file (with the token) in C:\Users\myName . How do I proceed?

**Comment by anishathalye** [comment]
This is not how remote helpers are used. See the usage examples in the [README](https://github.com/anishathalye/git-remote-dropbox/blob/master/README.rst) as well as [this documentation on git remote helpers](https://git-scm.com/docs/git-remote-helpers).

**Comment by chess123mate** [comment]
I did not realize that "git remote helper" was a term, I thought you were just describing git-remote-dropbox. I was using the readme, but it didn't clarify this. Thanks for the link to the documentation, I eventually found the line that said that git looks for the remote helpers automatically. What I didn't realize was that git wouldn't normally understand what "dropbox://" meant - I just thought it was a special path. (I had to paste the executable into the path from "git --exec-path"; I doubt that's what you're supposed to do, but git no longer tells me it can't find the remote helper for dropbox.)

It now has the output "Cloning into 'GitTest'..." and then it just hangs. I've let it run for many minutes. In the destination folder, it has created ".git" with a size of 14.3KB where-as the source .git is 15.6KB (when I try cloning without using the helper, the destination .git is 15.7KB). The helper has not copied over the single .txt file I added to the project (it contains just a couple words).

Does git-remote-dropbox.exe have other depencies that it doesn't have since I've copied the executable to a different path? Is there a command I can use to help figure out what's going on?

**Comment by anishathalye** [comment]
Ideally, you'd just update your `$PATH` to include the git-remote-dropbox binary wherever it's installed by pip or whatever, rather than manually moving the binary.

What do you mean by "where-as the source .git is 15.6KB"?

git-remote-dropbox's on-disk format isn't the same as Git's on-disk format. You can't use git-remote-dropbox to clone a repository directory that you've copy-pasted into your Dropbox. The way you put a new repo on Dropbox is to create a new git remote and push it to Dropbox using the helper.

**Comment by chess123mate** [comment]
(By "source" I meant the test project in Dropbox.)

If I understand you correctly, the correct thing to do is to push a local repository into Dropbox. I moved my "GitTest" project from Dropbox into my test folder (C:\GitTest), then ran ' git remote add origin "dropbox://GitTest" ' (from C:\GitTest), and then attempted "git push origin master". I have tried this with the following:

- The folder Dropbox/GitTest completely empty
- The folder Dropbox/GitTest with git initialized (as if a new project)
- The folder Dropbox/GitTest deleted

and git hangs each time with no ouptut and no Dropbox file changes.

**Comment by anishathalye** [comment]
What happens if you run `GIT_TRANSPORT_HELPER_DEBUG=1 git <something> -v` (so enable transport helper debugging and enable verbose output)? What's the output of running a command like that?

**Comment by chess123mate** [comment]
Thanks very much! Once I activated that debug command, the output was identical to issue #13 and so I realized that I needed to update my Git for Windows (which was 4 years old). Once I did that, everything started working.

**Comment by anishathalye** [comment]
Oh interesting! Glad you got it working finally.
