### ISSUE TITLE
Clarification as to 'Dropbox API app with full access'

### ISSUE THREAD

**Issue by njm2112** [anishathalye/git-remote-dropbox#54]
I'm hoping that `git-remote-dropbox` will work just fine with an API token generated for a Dropbox App that gets full access to a single folder for that app, but based on the current documentation, that's not clear:

> Generate an OAuth 2 token by going to the app console, creating a Dropbox API app with full access to all files and file types, and generating an access token for yourself.

There's also the possibility that granting full access to the App folder will work but is not the ideal setup; if so, adding that explanation to the documentation would be helpful. (I'd also like to know this, so if that's the case, a reply here would be appreciated!)

Thanks!

**Comment by anishathalye** [comment]
Hmm, I don't know if it works. If you want to experiment with that and let me know if it works, that would be awesome!

**Comment by fhcflx** [comment]
Yes, it works pretty much well!
