### ISSUE TITLE
Using git-remote-dropbox with Intellij IDEA

### ISSUE THREAD

**Issue by haimivan** [anishathalye/git-remote-dropbox#56]
Hi,

is it possible to use git-remote-dropbox directly within Intellij IDEA?

If yes, how would I have to set it up inside IDEA?

Thanks!

**Comment by anishathalye** [comment]
It should be possible to make it work. I don't use IDEA, so I don't know how to set it up. Probably just make sure it's on your `$PATH` and it should work.

**Comment by dconathan** [comment]
I use Intellij IDEA with git-remote-dropbox... seems to work like it would with any other remote upstream.
