### ISSUE TITLE
[feature request] Multiple OAuth token

### ISSUE THREAD

**Issue by scollovati** [anishathalye/git-remote-dropbox#59]
It would be great to have access to multiple Dropbox folders in these two ways:
- different Apps in the same Dropbox Account
- different Apps in different Dropbox Accounts 

I'm asking this because the token is saved in a global configuration file: I was wondering if it's possibile to have different local and global configurations as happens for `.gitconfig`

**Comment by anishathalye** [comment]
Someone started on implementing something like this - see #55

**Comment by scollovati** [comment]
Wow, really cool!
I'll follow the development.

Thanks!

**Comment by anishathalye** [comment]
Well, I don't think it's being worked on anymore by the original author, but if you'd like to pick up where that person left off (or just implement a separate solution and send a PR), that would be cool

**Comment by scollovati** [comment]
Actually I don't think to have the skills for doing that :)
I was just looking at the code and trying to understand how it works: I don't understand how the username associated to the token is generated.

**Comment by anishathalye** [comment]
Ok, no worries!

Even submitting this issue has been helpful -- now I know that there are multiple people who want this feature 😄

**Comment by scollovati** [comment]
That's fine ;)

I'm sorry that _isubas_ is no more developing it.

**Comment by gene-pavlovsky** [comment]
I'd also like to have multi-account support.
I have personal projects that I want to store in my personal dropbox, and work projects that I want to store in the team's business dropbox.
To me it would make sense if each dropbox oauth token could be assigned an id, and the URLs would look like `dropbox://id/path/to/project.git`.
I have no Python skills myself, but if the aforementioned PR is quite simple and just needs a few fixes, would probably be able to do that with your suggestions.

**Comment by anishathalye** [comment]
Okay, I implemented multi-account support in the `develop` branch: https://github.com/anishathalye/git-remote-dropbox/tree/develop

Anyone wanna try it out and give me feedback?

**Comment by gene-pavlovsky** [comment]
Hey, thanks a lot!

I've tried it out and it seems to work (mostly) fine.

I now have two usernames with tokens in my config file.
I've updated the work project to use the dropbox business token, and was able to pull from that remote.
I've created a new test project on one computer, commited a few files, set remote to the personal dropbox, then pushed. 

Saw this output:
```
C:\project\git-remote-dropbox\grd-test # git push -u origin master
Writing objects: 100% (8/8), done.
To dropbox:///git/project/grd-test.git
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin.
```

Notice that `To dropbox:///git/project/grd-test.git` doesn't mention the username, the actual url is `dropbox://heilong@/git/project/grd-test.git`.

Then, on another computer:
```
$ git clone dropbox://heilong@/git/project/grd-test.git
Cloning into 'grd-test'...
Receiving objects: 100% (8/8), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

I'm not sure why there is a warning about the remote HEAD?
The checked out `grd-test` wasn't on any branch, and was empty (besides `.git`), but I was able to `git checkout master`.

P.S. Is it a feature that I'm able to
`git clone dropbox://heilong@/git/some-nonexistent-repo.git` (which is cloned as an empty repo)?
It looks like a feature, but it's not explicitly mentioned in the README.

**Comment by anishathalye** [comment]
Cool! See #1 for more info about the warning about remote HEAD.

Yeah, it's a feature that you can clone a nonexistent repo. It's not super useful, so it's not documented anywhere.

Yeah, we can't count objects up front -- we're basically following the history pointers back, and so there's no way to tell how many objects we're going to need to download.

**Comment by gene-pavlovsky** [comment]
Yeah I already found #1 .
Got it. So, it appears the new feature is fully fine :)
One question - once you release this new version, what's gonna happen with the repositories using `dropbox://path/to/repo.git` URL format of the newer version? Will they need their remote URLs updated to the new syntax? Or would git-remote-dropbox somehow automatically update them?

**Comment by anishathalye** [comment]
Yeah, I think it's best to require the user to update to the newer syntax.

The new version does tell the user: `error: URLs with no username or token must start with "dropbox:///` if they're using the old scheme.

**Comment by gene-pavlovsky** [comment]
Cool. Well, thanks again for implementing this :)

**Comment by scollovati** [comment]
Thanks a lot for implementing this :))))
