### ISSUE TITLE
[feature request] Checkout on Dropbox

### ISSUE THREAD

**Issue by renxida** [anishathalye/git-remote-dropbox#60]
I have no idea how dropbox or git works, and I'm not sure if I'm supposed to submit this as an issue, but when I push to dropbox, only the object and ref folders appeared. I wonder if I could somehow also do a checkout when I do that push, so that my non-git teammates can at least read my code.

**Comment by anishathalye** [comment]
That is intentional - you're not supposed to mess with the files git-remote-dropbox generates. Having a checkout wouldn't make sense -- you'd lose all the correctness guarantees provided by git-remote-dropbox.
