### ISSUE TITLE
Update Dropbox Python SDK

### ISSUE THREAD

**Issue by gene-pavlovsky** [anishathalye/git-remote-dropbox#62]
Got this e-mail from dropbox:

___
We are reaching out to you because we have discovered an issue with the Dropbox API v2 Python SDK that your app is currently using. Although the issue does not break any existing behavior, it limits our ability to make non-breaking changes to our API endpoints going forward.

For that reason, we ask that you update your app to the latest version of the SDK within the next two months. This bug was fixed specifically in v8.0.0.

If you do not update SDK versions within the next two months, return types from some endpoints may fail to deserialize correctly, raising a runtime exception.
___

I suppose they might have notified you as well. Hope updating to the new SDK is not a big hassle.
Thanks!

**Comment by anishathalye** [comment]
Thanks for pointing this out!

I'll take a look over the next couple days. As you said, hopefully, it doesn't take much effort to update to the latest SDK version.

**Comment by anishathalye** [comment]
Okay, done!

**Comment by gene-pavlovsky** [comment]
That was quick! Thanks :)
