### ISSUE TITLE
Support restricted dropbox permissions

### ISSUE THREAD

**Issue by rkhwaja** [anishathalye/git-remote-dropbox#63]
The readme recommends creating an app with access to all of dropbox rather than using the "app folder" option. I would feel more comfortable if I could restrict the app's access to my other dropbox stuff.

**Comment by anishathalye** [comment]
#54 shows that app folders work too. I updated the readme (bdc8128110e4946a155cf5ab4b27f7da7eefffc5) to indicate this.

Thanks for pointing this out!
