### ISSUE TITLE
More descriptive errors

### ISSUE THREAD

**Issue by rkhwaja** [anishathalye/git-remote-dropbox#64]
I've been pushing my initial repositories and it takes a while for some of them. Some of them give the error "error: failed to push some refs to...". I assumed that this was just some dropbox timeout or whatever.
However, I've found that it also gives this error when I try to push to dropbox when there are remote changes that I haven't incorporated. As I remember, git usually gives a more descriptive error when this happens.
I see in the [git remote help](https://git-scm.com/docs/git-remote-helpers) that the call to push is supposed to return `error <dst> why>`, which it appears to be doing. What's going wrong?

**Comment by anishathalye** [comment]
Could you give more details on what exactly git-remote-dropbox prints (perhaps with some names censored, if you want), and also what you expect it to be printing?

**Comment by rkhwaja** [comment]
`git push dropbox master` prints
```
Writing objects: 100% (3173/3173), done.
To dropbox:///git/reponame
 ! [remote rejected] master -> master (non-fast-forward)
error: failed to push some refs to 'dropbox:///git/reponame'
```

I think if you use a filesystem-based dropbox "remote" repo you get:
`rejected master-> master (fetch first), failed to push some refs.... because remote contains work you do not have locally`
**It's the last part ("because remote contains work...") that is missing.**

btw, the debug output looks like:
```
Pushing to dropbox:///git/reponame
debug: fetching: /git/docs/refs/heads/master
debug: writing: /git/docs/objects/d1/<some hash>
...
debug: writing: /git/reponame/objects/db/<some other hash>
To dropbox:///git/reponame
 ! [remote rejected] master -> master (non-fast-forward)
error: failed to push some refs to 'dropbox:///git/reponame'
```

**Comment by anishathalye** [comment]
Huh, the "because remote contains work" part seems like it should be generated by git, not by the remote helper.

**Comment by rkhwaja** [comment]
In the [git source code](https://github.com/git/git/blob/e629a7d28a405e48fae6b064a781a10e885159fc/transport-helper.c), it looks like it's keying off the exact return message "fetch first". You do return that message if the error is a upload error but not for other errors. Could that be related?

**Comment by IcePhoenX** [comment]
Reading the linked source, the issue seems to be that git except `non-fast forward` as the why, and currently it receives `non-fast-forward`.
It's funny because the error that is generated from the single dash is containing two dashes.
BTW the remote helper is incorrectly reporting `non-fast-forward` even when it should be just `fetch first`.
