### ISSUE TITLE
Installation on Ubuntu 17.04

### ISSUE THREAD

**Issue by nihal78** [anishathalye/git-remote-dropbox#71]
Hi 

I am continuously getting "fatal: Unable to find remote helper for 'dropbox'" while trying to run a "git clone dropbox:///.....".
Has anyone else encountered this error? are there any fixes?

P.S. please pardon me if this is not the right place to raise this issue. please direct me to the correct place.

**Comment by anishathalye** [comment]
You need to make sure the tool is on your `$PATH`
