### ISSUE TITLE
Instructions on how to interact with full repos

### ISSUE THREAD

**Issue by Armagedoom** [anishathalye/git-remote-dropbox#72]
Hi:

I miss instructions on how to list / remove repositories from remote.
The main README.md clearly states not to interact with the dropbox folders.
So how should we remove old / broken repositories?
How should we list them?

I think those instructions would be very welcome in the main README.md.

Thanks again for this awesome repo btw :)

**Comment by anishathalye** [comment]
Repositories are just folders -- if you want to list them, you can look for them in your Dropbox folder. If you want to delete a repository, you can delete its folder.

**Comment by Armagedoom** [comment]
Awesome, thanks!!
