### ISSUE TITLE
How to use git-remote-dropbox behind socks5 proxy?

### ISSUE THREAD

**Issue by yanghaoxie** [anishathalye/git-remote-dropbox#77]
I can only connect to Dropbox behind a socks5 proxy. Is there any method to achieve this?

**Comment by anishathalye** [comment]
I think so. Could you try setting the appropriate environment variables according to this: http://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by yanghaoxie** [comment]
This method works great. Thanks so much!
It would be nice to add it to the document.

**Comment by anishathalye** [comment]
Note added to FAQ in dc1304844447eb3e425494aec1b49a431e87fa03.
