### ISSUE TITLE
Bug-Report: fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by ChausseBenjamin** [anishathalye/git-remote-dropbox#79]
When initially pushing `git push --set-upstream origin master`, I receive the following:

```
fatal: 'dropbox///A/Personnal/Miscellaneous/git-private/brnl.git' does not appear to be a git repository
fatal: Could not read from remote repository.
```
My API key was set in Dropbox and was correctly inserted in the `.json` file.

I used the method below to setup my repo only changing 

`git remote add origin ~/Dropbox/git/brnl.git` 

to 

`git remote add origin "dropbox///A/Personnal/Miscellaneous/git-private/brnl.git"`
```
~/project $ git init
~/project $ git add .
~/project $ git commit -m "first commit"
~/project $ cd ~/Dropbox/git

~/Dropbox/git $ git init --bare brnl.git
~/Dropbox/git $ cd ~/project

~/project $ git remote add origin ~/Dropbox/git/brnl.git
~/project $ git push -u origin master
```
-   git_remote_dropbox version: 1.0.8
-   git version 2.17.2 (Apple Git-113)
-   macOS 10.13.3 (High Sierra)

**Comment by echuber2** [comment]
You need to specify the remote with this kind of URI: `dropbox:///whatever/stuff.git` where the `///` begins the root of your Dropbox home as you would see it after logging into Dropbox on the web. So if you go on Dropbox and you have a `whatever` folder with a `stuff.git` subdirectory, there you go.

I believe that this plugin will automatically create the subdirectory if it doesn't exist, and you don't want to also sync that directory with the Dropbox client, so what I did was make a `/gitroots` on Dropbox, choose not to have that synced locally in the Dropbox client, and then put repos under that remote directory.
