### ISSUE TITLE
IDEA: Instructions for absolute beginners

### ISSUE THREAD

**Issue by ChausseBenjamin** [anishathalye/git-remote-dropbox#80]
The setup process was tedious for me as I'm an absolute beginner with git...

I made this `.md` file that I think could be useful:
[README.md.zip](https://github.com/anishathalye/git-remote-dropbox/files/2627379/README.md.zip)

It's basically a super dumbed down instruction manual so that someone that only knows `git commit` and `git push` can set himself up.

Feel free to attach it as a reference if it can help others!

**Comment by ChausseBenjamin** [comment]
Forgot to mention in the README: All my git repositories are stored in `./git-private` inside Dropbox...
You might want to specify that...

**Comment by anishathalye** [comment]
Great idea! I'll think about how to incorporate this information into the project. This is already kind of covered in the README (but not in as much detail). Perhaps we could create a [wiki](https://github.com/anishathalye/git-remote-dropbox/wiki), put this content there, and add a link to the page in the README.

I'm a bit busy over the next two weeks, but I should be able to get around to this afterwards.

**Comment by ChausseBenjamin** [comment]
Cool!

**Comment by anishathalye** [comment]
Oh we should leave this issue open till the content is put somewhere

**Comment by anishathalye** [comment]
I added your beginner's guide in our wiki: https://github.com/anishathalye/git-remote-dropbox/wiki

Thanks for the writeup!
