### ISSUE TITLE
Can this tool be used on OneDrive, too?

### ISSUE THREAD

**Issue by ColdCactus** [anishathalye/git-remote-dropbox#81]
Basically, as per the title. 
If not, are you aware of alternatives for OneDrive?

Many thanks!

**Comment by anishathalye** [comment]
Nope, not aware of something similar for OneDrive.

If there's an API for OneDrive and it contains an atomic compare-and-swap command (or equivalent), this should be pretty easy to do in theory, reusing most of the code in git-remote-dropbox.

**Comment by k-eex** [comment]
There's API for OneDrive:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online

The documentation does not say anything about atomicity, but the API is same as for SharePoint etc, which are heavily multi-user, so I would assume it does support basic concurrency features?

**Comment by k-eex** [comment]
After checking it more, in my opinion there is such a feature:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_update?view=odsp-graph-online
There's option of "if-match" header that should give the equivalent of atomic compare-update (it would fail when ctag of the object to be updated is not matched)

**Comment by anishathalye** [comment]
Oh that's interesting! So it looks like it's possible.

I don't personally have the bandwidth to implement this for OneDrive, but if someone else wants to do it, that would be neat. Feel free to fork git-remote-dropbox and make git-remote-onedrive :)
