### ISSUE TITLE
Missing step in this project's Wiki

### ISSUE THREAD

**Issue by VincentTam** [anishathalye/git-remote-dropbox#85]
Thanks for great tool, but I've encounter the same error as in #71.  The suggestion is _neither_ written in README nor in Wiki's beginner guide.

> "You need to make sure the tool is on your `$PATH`."

I tried adding `/home/vin100/.local/lib/python3.6/site-packages/git_remote_dropbox` to my ZSHRC, and my `PATH` reads

```
$ echo $PATH
/home/vin100/.nvm/versions/node/v10.10.0/bin:/opt/julia-1.1.0/bin:/home/vin100/.local/lib/python3.6/site-packages/git_remote_dropbox:/home/vin100/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ ls -l /home/vin100/.local/lib/python3.6/site-packages/git_remote_dropbox/           
total 32
-rw-rw-r-- 1 vin100 vin100 27100 May 12 17:28 __init__.py
drwxrwxr-x 2 vin100 vin100  4096 May 12 17:28 __pycache__
```

* * *

Edited: I've figured this out.  The tool has been installed as `~/.local/bin/git-remote-dropbox`.  Anywyays, a reminder like the one in the blockquote above would be informative.

**Comment by anishathalye** [comment]
Yes, this is a good point; #87 tries to address this. Let me know what you think of that PR.

**Comment by VincentTam** [comment]
That's concise and to the point :)
