### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/git-remote-dropbox#9]
We don't always show great error messages to the user for certain things. For example, if the OAuth token is incorrect, all that ends up getting reported is "unexpected exception".

It would be really valuable to users if there were better error messages, especially for common situations.

This issue can serve as a place to collect the situations where we want better error reporting.

**Comment by b-long** [comment]
:+1:

**Comment by anishathalye** [comment]
Finally improved in 2a89b73fd26b8dd632155cfe05f3c55ac64378c4! (not sure why this took so long 😛)
