### ISSUE TITLE
Saving OAuth token

### ISSUE THREAD

**Issue by lijiayi9712** [anishathalye/git-remote-dropbox#91]
Hi, I am trying to setup git-remote-dropbox following https://github.com/anishathalye/git-remote-dropbox/blob/master/README.md. However, I am really confused about where should I save the OAuth token that I generated from step 2. I am using a mac and where can I find '~/.config/git/git-remote-dropbox.json or ~/.git-remote-dropbox.json'? 

Thank you very much!

**Comment by anishathalye** [comment]
The `~` refers to your home folder. https://support.apple.com/guide/mac-help/go-directly-to-a-specific-folder-on-mac-mchlp1236/mac

**Comment by lijiayi9712** [comment]
Thanks! But I actually only found a 'ignore' file under '~/.config/git/'. Should I create aa json file with the OAuthen information? Or is there something wrong with my installation? I installed with pip.

**Comment by anishathalye** [comment]
Yes you will need to create the file

**Comment by lijiayi9712** [comment]
Thx a lot! I am wondering should i also put App key/secret somewhere? 

Also, do you mind explaining how to specify "dropbox://username@/path/to/repo" or "dropbox:///path/to/repo". I am quite confused about this format.

Really appreciate your help!

**Comment by lijiayi9712** [comment]
Hi, thanks for your help! I think the setup works but I am kind of curious about how to connect the repo to GitHub after connecting it to Dropbox? As currently, I can do everything that I can do with GitHub but unable to track the earlier changes to the folder. Thanks a lot!

**Comment by anishathalye** [comment]
I'm not sure what you mean by being unable to track earlier changes.

You can use the `git` command-line tool to interact with the repository history. Unlike GitHub, git-remote-dropbox will not give you a web interface.

**Comment by lijiayi9712** [comment]
Got it. Thanks a lot!
