### ISSUE TITLE
Pip package on PyPI out of date?

### ISSUE THREAD

**Issue by echuber2** [anishathalye/git-remote-dropbox#93]
I noticed that the [online pip package](https://pypi.org/project/git-remote-dropbox/) for this has an older than latest version of the Dropbox library specified as a requirement, so it forces a downgrade of that. The version of the setup script on the repo here has that requirement updated to the latest though. Are there any issues running with the latest version of the dropbox library?

**Comment by anishathalye** [comment]
That was not intentional, I just forgot to upload to PyPI. Thanks for the reminder. Version bumped in 9663ec9036681be4e1257d5d2c7d6a9277236357, uploaded to PyPI as [git-remote-dropbox 1.1.2](https://pypi.org/project/git-remote-dropbox/1.1.2/).

**Comment by echuber2** [comment]
Thanks!
