### ISSUE TITLE
syncthing

### ISSUE THREAD

**Issue by dtxl** [anishathalye/git-remote-dropbox#96]
I wonder whether this solution for dropbox would also be adaptable for the [Syncthing](https://github.com/syncthing) project. Thanks.

**Comment by anishathalye** [comment]
I don't know anything about Syncthing. In theory, if it supports primitives similar to Dropbox (including the "compare and swap" style operation), then it should be possible. This isn't something I'm interested in developing, but feel free to fork git-remote-dropbox if it works for your purposes.
