### ISSUE TITLE
Questions (probably for the FAQ)

### ISSUE THREAD

**Issue by mzbik** [anishathalye/git-remote-dropbox#97]
1. Once you create the app, you need to add permissions before you can do anything.
2. I have a laptop and desktop with the same logon.  Can I use the same OAuth token from both machines?
3. Clarify usage of multiple dropbox accounts vs sharing the repo folder.  "You can create OAuth tokens for different accounts": how do you do this?

Perhaps doing a walk-through with the current Dropbox and git-remote-dropbox on a virgin machine might show where more documentation is needed.

**Comment by anishathalye** [comment]
That's a good idea, I'll add it to my todo list (or feel free to send a PR).

In case you were wondering the answer to (2), it's fine to use the same OAuth token on multiple machines.

**Comment by mzbik** [comment]
See pr #98

**Comment by anishathalye** [comment]
Merged #98!
